FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend backend
COPY frontend frontend
CMD ["streamlit", "run", "frontend/streamlit_app/app.py", "--server.address", "0.0.0.0"]
